### ISSUE TITLE
Delete events

### ISSUE THREAD

**Issue by pkpowell** [jrvarma/icalcli#2]
Hi
Is it possible to delete events prior to a date with icalcli?
I have a few large .ics files and would like to purge events prior to 2000 before importing them into Outlook.

**Comment by jrvarma** [comment]
The delete command (`d`) has three arguments: search pattern, start date and end date. So using an empty pattern, a very old start date, and an end date of `today` should delete all events till today:

```
d '' 1900-00-01 today
```

- This is safe since it asks for confirmation after listing all matching events
- But you could also test it with a more recent start date like `2021-06-01` instead of `1900-00-01` before doing the real thing. 
- You could also first try the search command `s` instead of the delete command `d` to be sure that you have got things right.
- You could also use an end date like `2020-06-01` instead of `today`  if you want to retain last one year's events.
